@startuml typologie-microservices-05
!include <C4/C4_Deployment>
LAYOUT_TOP_DOWN()

Person(user, "Utilisateur interne/externe")

Container(front1, "Frontal Application F1", "React.js (SPA=Single Page Application)")
Container(front2, "Frontal Application F2", "PHP (SSR= Server Side Rendering)")

Container(api1, "API Rest A1", "")
Container(api2, "API GraphQL A2", "")
Container(api3, "API gRPC A3", "<sans persistence>")
ContainerDb(db_api1, "Base A1", "Oracle")
ContainerDb(db_api2, "Base A2", "PostgreSQL")
ContainerQueue(queue1, "Queue1", "Kafka")
Container(job1, "Job 1", "Spring Batch")

user -> front1 : utilise
user -> front2 : utilise

Rel(api1,db_api1,"sqlnet")
Rel(api2,db_api2,"pg")

Rel(front1,api1,"appelle", "HTTP(S)")
Rel(front1,api2,"appelle", "HTTP(S)")
Rel(front2,api3,"appelle", "HTTP(S)")
Rel(front2,api1,"appelle", "HTTP(S)")
Rel(api2,api3,"appelle", "HTTP(S)")
Rel(api2,queue1,"produit messages", "kafka")
Rel(api1,queue1,"consomme messages", "kafka")
Rel(job1, queue1,"consomme messages en asynchrone", "kafka")
Rel(job1, api2,"appelle en maj", "HTTP(S)")

@enduml
