@startuml typologie-monolithe-03
!include <C4/C4_Deployment>
LAYOUT_TOP_DOWN()
SHOW_PERSON_PORTRAIT()

Person(user, "Utilisateur interne/externe")

' Frontaux inchangés
Container(app1, "Application A1 (couches présentation/services/infrastructure)", "JSP (Java Server Pages)")
Container(app2, "Application A2", "PHP")

' Bases de données
ContainerDb(base1, "Base A1", "Oracle")
ContainerDb(base2, "Base A2", "DB2")

' Relations utilisateur
Rel(user, app1, "utilise", "HTTP(S)")
Rel(user, app2, "utilise", "HTTP(S)")

' Appels frontaux vers le monolithe
Rel(app1, base1, "appelle", "sqlnet")
Rel(app2, base2, "appelle", "db2")

Node(serveur_background, "(Optionnel) ETL, serveur de batchs") {
 Container(background, "ETL (ex: DataStage, Pentaho... ), jobs maison, ..." ,"Service batch/ETL") 
}

Rel(background,base1, "Synchronisation / chargement / traitements")
Rel(background,base2, "Synchronisation / chargement / traitements")

@enduml